version: '3'
services:
  frontend:
    container_name: my-shop-frontend
    image: frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
   
    ports:
      - 8080
    expose:
      - 5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend:
    container_name: myshop-backend
    image: backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/myshop
    
    ports:
      - 4444:4444
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
  mongo:
    container_name: sose-mongo
    image: mongo
    ports:
      - 27019:27017
  
